fix typo and add some options
immortalwrt/homeproxy pull request #160
Opened 2024-08-22 08:49 UTC by muink

2024-08-22 09:24 UTC, 1715173329 commented on root/etc/config/homeproxy
> +	option udp_timeout '5m'
Please use `seconds` as unit like other configurations.

2024-08-22 09:51 UTC, 1715173329 requested changes
1st commit title shoud start with `feat(generator/client):`
3rd commit title should start with `feat(generator):`

2024-08-22 09:51 UTC, 1715173329 commented on htdocs/luci-static/resources/view/homeproxy/node.js
> +	o = s.option(form.Flag, 'proxy_protocol', _('PROXY Protocol'),
```suggestion
	o = s.option(form.Flag, 'proxy_protocol', _('Proxy protocol'),
```

2024-08-22 09:51 UTC, 1715173329 commented on htdocs/luci-static/resources/view/homeproxy/node.js
> +		_('Write Proxy Protocol in the connection header.'));
```suggestion
		_('Write proxy protocol in the connection header.'));
```

2024-08-22 09:51 UTC, 1715173329 commented on htdocs/luci-static/resources/view/homeproxy/node.js
> +	o.default = o.disabled;
```suggestion
```
it's always default disabled

2024-08-22 09:51 UTC, 1715173329 commented on htdocs/luci-static/resources/view/homeproxy/node.js
> +	o = s.option(form.ListValue, 'proxy_protocol_version', _('PROXY Protocol version'));
```suggestion
	o = s.option(form.ListValue, 'proxy_protocol_version', _('Proxy protocol version'));
```

2024-08-22 11:52 UTC, 1715173329 commented on htdocs/luci-static/resources/view/homeproxy/client.js
> +			_('In seconds. <code>5m</code> is used by default.'));
```suggestion
			_('In seconds. <code>300</code> is used by default.'));
```

2024-08-22 11:52 UTC, 1715173329 commented on htdocs/luci-static/resources/view/homeproxy/client.js
> +		so.default = '300';
```suggestion
		so.placeholder = '300';
```

since it cannot be empty. tbh do we really need to specify a preset value instead of leaving it default (empty)?

2024-08-22 12:14 UTC, muink commented on htdocs/luci-static/resources/view/homeproxy/client.js
> +		so.default = '300';
keep empty is not bad. i will modify it

2024-08-22 12:46 UTC, 1715173329 reviewed
based on the discussion

2024-08-22 12:46 UTC, 1715173329 commented on htdocs/luci-static/resources/view/homeproxy/client.js
> +		so.placeholder = '300';
```suggestion
		o.default = '300';
```

2024-08-22 12:46 UTC, 1715173329 commented on htdocs/luci-static/resources/view/homeproxy/server.js
> +		o.placeholder = '300';
```suggestion
		o.default = '300';
```

2024-08-22 12:46 UTC, 1715173329 commented on root/etc/config/homeproxy
> +	option udp_timeout '300'
```suggestion
	option udp_timeout ''
```

2024-08-22 12:46 UTC, 1715173329 commented on root/etc/homeproxy/scripts/generate_client.uc
> +udp_timeout = uci.get(uciconfig, 'infra', 'udp_timeout') || '300';
```suggestion
udp_timeout = uci.get(uciconfig, 'infra', 'udp_timeout');
```

2024-08-22 12:46 UTC, 1715173329 commented on root/etc/homeproxy/scripts/generate_client.uc
> +	udp_timeout = uci.get(uciconfig, uciroutingsetting, 'udp_timeout') || '300';
```suggestion
	udp_timeout = uci.get(uciconfig, uciroutingsetting, 'udp_timeout');
```

2024-08-22 12:46 UTC, 1715173329 commented on root/etc/homeproxy/scripts/generate_client.uc
> +	udp_timeout: udp_timeout + 's',
```suggestion
	udp_timeout: udp_timeout ? (udp_timeout + 's') : null,
```

2024-08-22 12:46 UTC, 1715173329 commented on root/etc/homeproxy/scripts/generate_client.uc
> +		udp_timeout: udp_timeout + 's',
```suggestion
		udp_timeout: udp_timeout ? (udp_timeout + 's') : null,
```

2024-08-22 12:46 UTC, 1715173329 commented on root/etc/homeproxy/scripts/generate_client.uc
> +		udp_timeout: udp_timeout + 's',
```suggestion
		udp_timeout: udp_timeout ? (udp_timeout + 's') : null,
```

2024-08-22 12:58 UTC, 1715173329 approved these changes

2024-08-22 12:58 UTC, 1715173329 commented
LGTM, thanks

2024-08-23 07:22 UTC, merged

2024-08-29 12:53 UTC, muink commented on root/etc/homeproxy/scripts/generate_client.uc
> +		proxy_protocol: (node.proxy_protocol === '1') ? {
Looks like I made a mistake. The new patch has been committed
https://github.com/immortalwrt/homeproxy/commit/410c10eb4350c68959da9e75ed644d3821cd7953

2024-08-29 12:55 UTC, 1715173329 commented on root/etc/homeproxy/scripts/generate_client.uc
> +		proxy_protocol: (node.proxy_protocol === '1') ? {
Thanks for quick fix