add support for ech_config_path
immortalwrt/homeproxy pull request #238
Opened 2024-12-05 10:26 UTC by saldry

2024-12-05 10:44 UTC, 1715173329 requested changes

2024-12-05 10:44 UTC, 1715173329 commented on htdocs/luci-static/resources/view/homeproxy/node.js
> +		o.rmempty = false;
drop

2024-12-05 10:44 UTC, 1715173329 commented on root/etc/homeproxy/scripts/generate_client.uc
> -				config: node.tls_ech_config
should keep this for backwards compatibility

2024-12-05 10:50 UTC, saldry commented on root/etc/homeproxy/scripts/generate_client.uc
> -				config: node.tls_ech_config
updated

2024-12-05 13:13 UTC, 1715173329 approved these changes

2024-12-06 07:26 UTC, merged

2024-12-06 07:26 UTC, 1715173329 commented
Merged, thank you!