feat(generator/client): Add more options support
immortalwrt/homeproxy pull request #45
Opened 2023-11-16 03:05 UTC by muink

1. Add DNS global options
    - \+ dns.independent_cache
    - \+ dns.reverse_mapping
2. Add System DNS server `address: 'local'` for resolving custom private domain
    - \+ dns.servers[1]
3. DNS rules
    - \- homeproxy.@dns_rule[-1].ip_cidr
    - \+ dns.rules.query_type
    - \+ dns.rules.ip_version
    - \+ dns.rules.auth_user
    - \+ dns.rules.user_id
    - \+ dns.rules.clash_mode
    - \+ dns.rules.rewrite_ttl
    - Allow `dns.rules.outbound: 'any'`
3. Route rules
    - \+ route.rules.auth_user
    - \+ route.rules.user_id
    - \+ route.rules.clash_mode

2023-11-20 09:29 UTC, 1715173329 commented
- f6d1748: feat(client): dns.servers: Add system DNS
- 5765506: fix(client): dns.rules: Remove invalid option and update description
- 8b9053b: chore(client): dns.rules: Move option sequence
- af8aba0: feat(client): dns.rules: Allow outbound any

I've applied part of your changes, please rebase this PR then let's discuss the remaining ones.

2023-11-20 13:59 UTC, muink commented
I've rebased the branch and I think we can continue.

2023-11-27 09:28 UTC, muink commented
Can we continue with the rest?

2023-11-27 09:32 UTC, 1715173329 commented
So sorry I'm super busy these days and the review has to be delayed.

2023-11-30 08:32 UTC, 1715173329 requested changes

2023-11-30 08:32 UTC, 1715173329 commented on htdocs/luci-static/resources/view/homeproxy/client.js
> +		so = ss.option(form.DynamicList, 'auth_user', _('Auth user'),
this is unused in hp

2023-11-30 08:32 UTC, 1715173329 commented on htdocs/luci-static/resources/view/homeproxy/client.js
> +		so = ss.option(form.DynamicList, 'user_id', _('User ID'),
not much useful in openwrt

2023-11-30 08:32 UTC, 1715173329 commented on htdocs/luci-static/resources/view/homeproxy/client.js
> +		so = ss.option(form.ListValue, 'clash_mode', _('Clash mode'),
unused

2023-11-30 08:32 UTC, 1715173329 commented on htdocs/luci-static/resources/view/homeproxy/client.js
> +		so = ss.option(form.Flag, 'reverse_mapping', _('Reverse mapping'),
useless in our case

2023-11-30 08:32 UTC, 1715173329 commented on htdocs/luci-static/resources/view/homeproxy/client.js
> +		so = ss.option(form.DynamicList, 'auth_user', _('Auth user'),
unused

2023-11-30 08:32 UTC, 1715173329 commented on htdocs/luci-static/resources/view/homeproxy/client.js
> +		so = ss.option(form.DynamicList, 'user_id', _('User ID'),
useless

2023-11-30 08:32 UTC, 1715173329 commented on htdocs/luci-static/resources/view/homeproxy/client.js
> +		so = ss.option(form.ListValue, 'clash_mode', _('Clash mode'),
unused

2023-11-30 08:32 UTC, 1715173329 commented on htdocs/luci-static/resources/view/homeproxy/client.js
> +		so.validate = function(section_id, value) {
Unnecessary at all IMO. It can be done perfectly using custom CBI, but let's keep it simple.

2023-12-01 09:16 UTC, muink commented
Redundant options have been cleaned up

2023-12-02 06:58 UTC, muink reviewed
done

2023-12-02 08:09 UTC, 1715173329 requested changes

2023-12-02 08:09 UTC, 1715173329 commented on root/etc/homeproxy/scripts/generate_client.uc
>      direct_domain_list;
```suggestion
    dns_server, dns_default_strategy, dns_default_server, dns_disable_cache, dns_disable_cache_expire,
    dns_independent_cache, direct_domain_list;
```

2023-12-02 08:42 UTC, 1715173329 approved these changes

2023-12-02 08:42 UTC, merged